// export const fakedata = [
//   {
//     id: 1,
//     song: "The Sliding Mr. Bones (Next Stop, Pottersville)",
//     artist: "Malcolm Lockyer",
//     year: 1961,
//   },
//   {
//     id: 2,
//     song: "Memories Are Made of This",
//     artist: "Dean Martin",
//     year: 1955,
//   },
//   {
//     id: 3,
//     song: "Rock Around the Clock",
//     artist: "Bill Haley & His Comets",
//     year: 1954,
//     checked: false,
//   },
//   {
//     id: 4,
//     song: "Heartbreak Hotel",
//     artist: "Elvis Presley",
//     year: 1956,
//     checked: false,
//   },
//   {
//     id: 5,
//     song: "Great Balls of Fire",
//     artist: "Jerry Lee Lewis",
//     year: 1957,
//     checked: false,
//   },
//   {
//     id: 6,
//     song: "Johnny B. Goode",
//     artist: "Chuck Berry",
//     year: 1958,
//     checked: false,
//   },
//   {
//     id: 7,
//     song: "Blueberry Hill",
//     artist: "Fats Domino",
//     year: 1956,
//     checked: false,
//   },
//   {
//     id: 8,
//     song: "Peggy Sue",
//     artist: "Buddy Holly",
//     year: 1957,
//     checked: false,
//   },
//   {
//     id: 9,
//     song: "La Bamba",
//     artist: "Ritchie Valens",
//     year: 1958,
//     checked: false,
//   },
//   {
//     id: 10,
//     song: "Wake Up Little Susie",
//     artist: "The Everly Brothers",
//     year: 1957,
//     checked: false,
//   },
//   {
//     id: 11,
//     song: "All I Have to Do Is Dream",
//     artist: "The Everly Brothers",
//     year: 1958,
//     checked: false,
//   },
//   {
//     id: 12,
//     song: "Hound Dog",
//     artist: "Elvis Presley",
//     year: 1956,
//     checked: false,
//   },
//   {
//     id: 13,
//     song: "Tutti Frutti",
//     artist: "Little Richard",
//     year: 1955,
//     checked: false,
//   },
//   {
//     id: 14,
//     song: "Maybellene",
//     artist: "Chuck Berry",
//     year: 1955,
//     checked: false,
//   },
//   {
//     id: 15,
//     song: "Long Tall Sally",
//     artist: "Little Richard",
//     year: 1956,
//     checked: false,
//   },
//   {
//     id: 16,
//     song: "Jailhouse Rock",
//     artist: "Elvis Presley",
//     year: 1957,
//     checked: false,
//   },
//   {
//     id: 17,
//     song: "That'll Be the Day",
//     artist: "Buddy Holly",
//     year: 1957,
//     checked: false,
//   },
//   {
//     id: 18,
//     song: "Whole Lotta Shakin' Goin' On",
//     artist: "Jerry Lee Lewis",
//     year: 1957,
//     checked: false,
//   },
//   {
//     id: 19,
//     song: "Chantilly Lace",
//     artist: "The Big Bopper",
//     year: 1958,
//     checked: false,
//   },
//   {
//     id: 20,
//     song: "Shout",
//     artist: "The Isley Brothers",
//     year: 1959,
//     checked: false,
//   },
// ];

export const fakedata = [
  {
    id: 1,
    song: "The Sliding Mr. Bones (Next Stop, Pottersville)",
    artist: "Malcolm Lockyer",
    year: 1961,
    description:
      "A smooth jazz track with a lively rhythm, perfect for a chilled evening.",
  },
  {
    id: 2,
    song: "Fly Me to the Moon",
    artist: "Frank Sinatra",
    year: 1964,
    description:
      "A classic and timeless jazz standard with Sinatra's signature vocal delivery.",
  },
  {
    id: 3,
    song: "A Day in the Life",
    artist: "The Beatles",
    year: 1967,
    description:
      "An experimental rock song that showcases The Beatles' diverse musical styles.",
  },
  {
    id: 4,
    song: "Bohemian Rhapsody",
    artist: "Queen",
    year: 1975,
    description:
      "A progressive rock anthem with complex arrangements and operatic influences.",
  },
  {
    id: 5,
    song: "Imagine",
    artist: "John Lennon",
    year: 1971,
    description:
      "A peaceful and introspective ballad that envisions a world united without borders.",
  },
  {
    id: 6,
    song: "Purple Haze",
    artist: "Jimi Hendrix",
    year: 1967,
    description:
      "A psychedelic rock classic with a memorable guitar riff that defines Hendrix's unique style.",
  },
  {
    id: 7,
    song: "Stairway to Heaven",
    artist: "Led Zeppelin",
    year: 1971,
    description:
      "A rock epic that builds from a soft acoustic intro to a powerful electric guitar solo.",
  },
  {
    id: 8,
    song: "Billie Jean",
    artist: "Michael Jackson",
    year: 1982,
    description:
      "A pop-funk hit with a catchy bassline, showcasing Michael Jackson's iconic vocals and dance moves.",
  },
  {
    id: 9,
    song: "Smells Like Teen Spirit",
    artist: "Nirvana",
    year: 1991,
    description:
      "A grunge anthem that revolutionized the 90s rock scene with its raw energy and rebellious lyrics.",
  },
  {
    id: 10,
    song: "Hotel California",
    artist: "Eagles",
    year: 1976,
    description:
      "A rock ballad with haunting lyrics and a signature guitar solo that became a classic.",
  },
  {
    id: 11,
    song: "What's Going On",
    artist: "Marvin Gaye",
    year: 1971,
    description:
      "A soulful protest song addressing social issues and calling for peace and understanding.",
  },
  {
    id: 12,
    song: "Superstition",
    artist: "Stevie Wonder",
    year: 1972,
    description:
      "A funk-soul track driven by a groovy clavinet riff, showcasing Stevie Wonder's musical genius.",
  },
  {
    id: 13,
    song: "Tutti Frutti",
    artist: "Little Richard",
    year: 1955,
    checked: false,
  },
  {
    id: 14,
    song: "Maybellene",
    artist: "Chuck Berry",
    year: 1955,
    checked: false,
  },
  {
    id: 15,
    song: "Long Tall Sally",
    artist: "Little Richard",
    year: 1956,
    checked: false,
  },
  {
    id: 16,
    song: "Jailhouse Rock",
    artist: "Elvis Presley",
    year: 1957,
    checked: false,
  },
  {
    id: 17,
    song: "That'll Be the Day",
    artist: "Buddy Holly",
    year: 1957,
    checked: false,
  },
  {
    id: 18,
    song: "Whole Lotta Shakin' Goin' On",
    artist: "Jerry Lee Lewis",
    year: 1957,
    checked: false,
  },
  {
    id: 19,
    song: "Chantilly Lace",
    artist: "The Big Bopper",
    year: 1958,
    checked: false,
  },
  {
    id: 20,
    song: "Shout",
    artist: "The Isley Brothers",
    year: 1959,
    checked: false,
  },
];
