export const fakedata = [
  {
    id: 1,
    song: "The Sliding Mr. Bones (Next Stop, Pottersville)",
    artist: "Malcolm Lockyer",
    year: 1961,
  },
  {
    id: 2,
    song: "Memories Are Made of This",
    artist: "Dean Martin",
    year: 1955,
  },
  {
    id: 3,
    song: "Rock Around the Clock",
    artist: "Bill Haley & His Comets",
    year: 1954,
    checked: false,
  },
  {
    id: 4,
    song: "Heartbreak Hotel",
    artist: "Elvis Presley",
    year: 1956,
    checked: false,
  },
  {
    id: 5,
    song: "Great Balls of Fire",
    artist: "Jerry Lee Lewis",
    year: 1957,
    checked: false,
  },
  {
    id: 6,
    song: "Johnny B. Goode",
    artist: "Chuck Berry",
    year: 1958,
    checked: false,
  },
  {
    id: 7,
    song: "Blueberry Hill",
    artist: "Fats Domino",
    year: 1956,
    checked: false,
  },
  {
    id: 8,
    song: "Peggy Sue",
    artist: "Buddy Holly",
    year: 1957,
    checked: false,
  },
  {
    id: 9,
    song: "La Bamba",
    artist: "Ritchie Valens",
    year: 1958,
    checked: false,
  },
  {
    id: 10,
    song: "Wake Up Little Susie",
    artist: "The Everly Brothers",
    year: 1957,
    checked: false,
  },
  {
    id: 11,
    song: "All I Have to Do Is Dream",
    artist: "The Everly Brothers",
    year: 1958,
    checked: false,
  },
  {
    id: 12,
    song: "Hound Dog",
    artist: "Elvis Presley",
    year: 1956,
    checked: false,
  },
  {
    id: 13,
    song: "Tutti Frutti",
    artist: "Little Richard",
    year: 1955,
    checked: false,
  },
  {
    id: 14,
    song: "Maybellene",
    artist: "Chuck Berry",
    year: 1955,
    checked: false,
  },
  {
    id: 15,
    song: "Long Tall Sally",
    artist: "Little Richard",
    year: 1956,
    checked: false,
  },
  {
    id: 16,
    song: "Jailhouse Rock",
    artist: "Elvis Presley",
    year: 1957,
    checked: false,
  },
  {
    id: 17,
    song: "That'll Be the Day",
    artist: "Buddy Holly",
    year: 1957,
    checked: false,
  },
  {
    id: 18,
    song: "Whole Lotta Shakin' Goin' On",
    artist: "Jerry Lee Lewis",
    year: 1957,
    checked: false,
  },
  {
    id: 19,
    song: "Chantilly Lace",
    artist: "The Big Bopper",
    year: 1958,
    checked: false,
  },
  {
    id: 20,
    song: "Shout",
    artist: "The Isley Brothers",
    year: 1959,
    checked: false,
  },
];
